### ISSUE TITLE
ErrorException #64

### ISSUE THREAD

**Issue by tasdiek** [ilhamlutfi/starter-ci4#1]
Declaration of Myth\Auth\Filters\LoginFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = NULL) 

pada waktu di jalankan dengan php 7.3, debian 10

**Comment by ilhamlutfi** [comment]
Ini adalah salah satu bug di library Myth/Auth nya ketika selesai menjalankan composer update, silahkan tambahkan parameter  $arguments = NULL, di Filter/LoginFilter.php di dalam method before dan after
