### ISSUE TITLE
Error Exception

### ISSUE THREAD

**Issue by fdciabdul** [ilhamlutfi/starter-ci4#2]
![adsdas](https://user-images.githubusercontent.com/31664438/113535000-698bd100-95fc-11eb-9f21-07d7c8639965.PNG)

saya mengalami masalah ini saat menjalankan starter project ini , dan saya juga sudah ngikut saran mas di issue #1  
dengan menambahkan parameter ini di dalam library Myth Auth nya

tapi yang terjadi malah web gamau keload mas 

![q34234](https://user-images.githubusercontent.com/31664438/113535069-9cce6000-95fc-11eb-937d-c7503827af8a.PNG)

**Comment by ilhamlutfi** [comment]
Coba di akses dulu project nya di localhost:8080 setelah menjalankan php spark serve, Apa ada pesan error lain..?

**Comment by fdciabdul** [comment]
> Coba di akses dulu project nya di localhost:8080 setelah menjalankan php spark serve, Apa ada pesan error lain..?

gada mas , cuma accepted sama closing doang

**Comment by ilhamlutfi** [comment]
Memang seperti itu di terminal coba di akses di browser mas localhost:8080

**Comment by fdciabdul** [comment]
> Memang seperti itu di terminal coba di akses di browser mas localhost:8080

udah mas , gabisa keload .. error 500

**Comment by ilhamlutfi** [comment]
Harusnya gak ada masalah sih mas, Kalo bug myth/auth nya sudah solved, Kalo error 500 artinya internal server error coba check server requirment Codeigniter 4 mas, https://codeigniter.com/user_guide/intro/requirements.html

**Comment by ilhamlutfi** [comment]
Saya baru saja clone lagi mas starter projects nya, composer update lalu debug myth/auth nya, Kemudian php spark serve

rsud@rsud-inspiron:/opt/lampp/htdocs/starter-ci4-main$ php spark serve

CodeIgniter v4.1.1 Command Line Tool - Server Time: 2021-04-06 03:49:57 UTC-05:00

CodeIgniter development server started on http://localhost:8080
Press Control-C to stop.
[Tue Apr  6 15:49:57 2021] PHP 8.0.2 Development Server (http://localhost:8080) started

**Comment by fdciabdul** [comment]
> Saya baru saja clone lagi mas starter projects nya, composer update lalu debug myth/auth nya, Kemudian php spark serve
> 
> rsud@rsud-inspiron:/opt/lampp/htdocs/starter-ci4-main$ php spark serve
> 
> CodeIgniter v4.1.1 Command Line Tool - Server Time: 2021-04-06 03:49:57 UTC-05:00
> 
> CodeIgniter development server started on http://localhost:8080
> Press Control-C to stop.
> [Tue Apr 6 15:49:57 2021] PHP 8.0.2 Development Server (http://localhost:8080) started

di mas nya jalan lancar kah ? disaya masih sama sih gabisa keload , apa versi php nya harus update ke versi 8 ? 

soalnya project ci3 disaya masih lancar lancar aja , sementara ci4 selalu error gini

**Comment by ilhamlutfi** [comment]
Kalo versi php minimal 7.2 mas, Kalo di saya lancar aja
